# Generated by Django 3.2.6 on 2021-11-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211119_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkbtn_text', models.CharField(max_length=200)),
                ('linkbtn_link', models.CharField(max_length=200)),
                ('linkbtn_icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
