# Generated by Django 3.2.6 on 2021-12-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211122_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_description', models.CharField(max_length=200)),
                ('client_img', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='LinkBtn',
        ),
    ]
