# Generated by Django 3.2.6 on 2021-12-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211209_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client_website',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
